spring:
  datasource:
    url: jdbc:h2:file:./db/db
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
  h2:
    console:
      path: /h2
      enabled: true
